name: Manual Plugin Build

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
  build:
    runs-on: ubuntu-24.04  # Use the latest Ubuntu version

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Gradle Wrapper Verification
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Elevate wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Commit and push build artifact
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b temp-build
          git add build/libs/LightningPop-*.jar
          git commit -m "Add build artifact"
          git push --force https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} temp-build
