name: Manual Plugin Build

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
  build:
    runs-on: ubuntu-24.04  # Use the latest Ubuntu version
    strategy:
      matrix:
        branch: [master, 2b]  # Define branches for Java 21 and Java 17 builds
        java_version: [21, 17]  # Corresponding Java versions

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'

      - name: Elevate wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Copy Build Artifact
        run: |
          mkdir -p build/artifacts
          cp build/libs/LightningPop-*.jar build/artifacts/LightningPop-${{ matrix.branch }}.jar
          echo "Built artifact for branch: ${{ matrix.branch }} with Java ${{ matrix.java_version }}"
          
      - name: Commit and push build artifacts
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add build/artifacts/*
          git commit -m "Add build artifacts for ${{ matrix.branch }}"
          git push --force https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} temp-build
