name: Manual Plugin Build

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
  build-master:
    runs-on: ubuntu-24.04

    outputs:
      artifact_master: ${{ steps.upload_master.outputs.artifact-path }}

    steps:
      - name: Check out master branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Gradle Wrapper Verification
        uses: gradle/wrapper-validation-action@v1

      - name: Set executable permissions for gradlew
        run: chmod +x ./gradlew

      - name: Setup JDK for Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Plugin for Master (1.21.4)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload artifact for master branch (1.21.4)
        id: upload_master
        uses: actions/upload-artifact@v4
        with:
          name: LightningPop-master
          path: build/libs/LightningPop-*.jar

  build-2b:
    needs: build-master
    runs-on: ubuntu-24.04

    outputs:
      artifact_2b: ${{ steps.upload_2b.outputs.artifact-path }}

    steps:
      - name: Check out 2b branch
        uses: actions/checkout@v3
        with:
          ref: 2b

      - name: Gradle Wrapper Verification
        uses: gradle/wrapper-validation-action@v1

      - name: Set executable permissions for gradlew
        run: chmod +x ./gradlew

      - name: Setup JDK for Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Plugin for 2b (1.20.4)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload artifact for 2b branch (1.20.4)
        id: upload_2b
        uses: actions/upload-artifact@v4
        with:
          name: LightningPop-2b
          path: build/libs/LightningPop-*.jar
