name: Manual Release Creation

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get and increment latest tag
        id: get_tag
        run: |
          if git tag | grep .; then
            latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo "Latest tag: $latest_tag"
            version=${latest_tag#v}
            IFS='.' read -r major minor patch <<< "$version"
            new_patch=$((patch + 1))
            new_tag="v$major.$minor.$new_patch"
          else
            new_tag="v0.0.1"
          fi
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Verify gradlew exists
        run: ls -l ./gradlew

      - name: Create and push new tag
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag ${{ env.new_tag }}
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/GarlicRot/LightningPop.git ${{ env.new_tag }}

      - name: Build plugin
        run: bash ./gradlew build

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.new_tag }}
          release_name: ${{ env.new_tag }}
          body: |
            This is an automated release for version ${{ env.new_tag }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Plugin Jar
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/LightningPop-*.jar
          asset_name: LightningPop-${{ env.new_tag }}.jar
          asset_content_type: application/java-archive
